default: hellolinden
environments:
  hellolinden:
    type: ec2
    control-bucket: juju-faefb490d69a41f0a3616a4808e0766b
    admin-secret: 81a1e7429e6847c4941fda7591246594
    default-series: precise
    juju-origin: distro
    ssl-hostname-verification: true
    access-key: A
    secret-key: P
    
