default: hellolinden
environments:
  hellolinden:
    type: ec2
    control-bucket: hello-e420416f-2f96-4e35-a142-fa4674f8b603
    admin-secret: 81a1e7429e6847c4941fda7591246594
    default-series: precise
    juju-origin: ppa
    ssl-hostname-verification: true
    access-key: AKIAIG46SX7U62PZ7OIA
    secret-key: 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
    
